config/routes.rb
Rails.application.routes.draw do

  root 'drinks#index'
  resources :drinks

end

app/models/drink.rb
class Drink < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController

    def index
        @drinks = Drink.all
        if @drinks.count < 1
            redirect_to url_for(:controller => :drinks, :action => :new)
        end
    end
    
    def show
        @drink = Drink.find(params[:id])
    end

    def new #display form
        @drink = Drink.new
    end
    
    def create #save new record
        @drink = Drink.new(allowed_params)
        if @drink.save
            redirect_to drinks_path #index
        else
            redender 'new'
        end 
    end

    def edit
        @drink = Drink.find(params[:id])
        
        respond_to do |format|
            format.html # edit.html.erb
            format.json { render json: @drink }
        end
    end
    
    def update #save changes
        @drink = Drink.find(params[:id])
        if @drink.update_attributes(allowed_params)
            redirect_to drinks_path #index
        #else
            # redender 'edit' #new
        end 
    end
    
    def destroy
        @drink = Drink.find(params[:id])
        @drink.destroy
        redirect_to drinks_path
    end
    
    private
        def allowed_params
            params.require(:drink).permit(:name, :size)
        end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drinks_helper.rb
module DrinksHelper
end

app/views/drinks/edit.html.erb
<%= form_for @drink do |f| %>
    <%= f.label :name %><br/>
    <%= f.text_field :name %><br/>
    <br/>
    <%= f.label :size %><br/>
    <%= f.text_field :size %><br/>
    <%= f.submit %>
<% end %>

app/views/drinks/index.html.erb
<%= link_to 'Add Drink', new_drink_path, class: "col-md-1 btn btn-default" %>
</br>
</br>

<!--
In database: <%= @drinks.count %>
-->

<table class="table">

<thead>
    <tr>
        <th>ID</th>
        <th>Drink</th>
        <th>Size</th>
        <th>Action</th>
    </tr>
</thead>

<% @drinks.each do |drink| %>
    <tbody>
        <tr>
            <td>
                <%= drink.id %>
            </td>
            <td>
                <%= link_to drink.name, drink_path(drink) %>
            </td>
            <td>
                <%= drink.size %>
            </td>
            <td>
                <%= link_to 'Edit', edit_drink_path(drink), class: "btn btn-default" %>
                <%= link_to 'Delete', drink, method: :delete, class: "btn btn-space btn-danger" %>
            </td>
        </tr>
    </tbody>
<% end %>

</table>

app/views/drinks/new.html.erb
<%= form_for @drink, :html => {:class => "form-horizontal"} do |f| %>
    <div class="form-group">
        <%= f.label :name, "Drink:", class: "col-md-1 control-label" %>
        <div class="col-md-2">
          <%= f.text_field :name, class: "form-control" %>
        </div>
    </div>

    <div class="form-group">
        <%= f.label :size, "Size:", class: "col-md-1 control-label" %>
        <div class="col-md-2">
          <%= f.text_field :size, class: "form-control" %>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-1"></div>
        <%= link_to 'Go back', drinks_path, class: "col-md-1 btn btn-space btn-default" %>
        <%= f.submit "Save", class: "col-md-1 btn btn-space btn-default" %>
    </div>
    
<% end %>

app/views/drinks/show.html.erb
<%= @drink.name%><br/>
<%= @drink.size%><br/>
<%= link_to 'go back', drinks_path%>

app/views/layouts/_title.html.erb
<div class="page-header">
  <h1>Rails simple MVC app <small> CRUD operations and AUTH</small></h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="app-space">
  <%= render 'layouts/title' %>
  <%= yield %>
</div>

</body>
</html>